name: Preprocess Dataset

on:
  workflow_dispatch:
  push:
    paths:
      - 'preprocessing/automate_Dwi-Cahya_Nur-Faizi.py'
      - 'preprocessing/requirements.txt'

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run preprocessing script
        run: python preprocessing/automate_Dwi-Cahya-Nur-Faizi.py
      
      - name: Commit and push preprocessed datasets
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add preprocessing/personality_preprocessing/train.csv
          git add preprocessing/personality_preprocessing/test.csv

          git commit -m "Update train/test datasets from workflow run" || echo "No changes to commit"
          git push https://x-access-token:${GIT_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
        env:
          GIT_TOKEN: ${{ secrets.GH_PAT }}
